general.import = ["/home/rgregor/.config/alacritty/dracula_custom-3.toml"]

[font]
size = 12.0

[font.bold]
family = "Iosevka Nerd Font Mono"
# family = "MesloLGS Nerd Font Mono"
# family = "Iosevka Nerd Font Mono"
style = "Bold"

[font.italic]
family = "Iosevka Nerd Font Mono"
# family = "MesloLGS Nerd Font Mono"
# family = "Iosevka Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Iosevka Nerd Font Mono"
# family = "MesloLGS Nerd Font Mono"
# family = "Iosevka Nerd Font Mono"
style = "Regular"

[window.dimensions]
columns = 160
lines = 40

# [window.position]
# x = 60
# y = 50

# from:  https://alacritty.org/config-alacritty.html

[window.padding]
x = 10
y = 10

[window]
position = "None"
# dynamic_padding = true
# decorations = "Full"
decorations = "Full"
opacity = 0.9
blur = true
resize_increments = false

[cursor]
style.shape = "Block"
style.blinking = "Always"
